services:
  web:
    build: .
    volumes:
      - ./cache:/app/cache
      - ./db.sqlite:/app/db.sqlite
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - web
